### Application Root
GET http://localhost:3001


### Get List
GET http://localhost:3001/api/person/about

### Get List
GET http://localhost:3001/api/person


### Get record
GET http://localhost:3001/api/person/65eb0ee8e1e1af93be1c915b


### Post person
POST http://localhost:3001/api/person
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

### PUT person
PUT http://localhost:3001/api/person/2/0.9876


### DELETE person
DELETE http://localhost:3001/api/person/2

