### Application Root
GET http://localhost:3001


### Get List
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist


### Get List
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/full


### Get record
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319


### Post tasklist
POST http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/
Content-Type: application/json

{
    "name": "Sprint 1"
}

### PUT tasklist
PUT http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65eb29faef4f5956065e7235
Content-Type: application/json

{
    "name": "Sprint 11"
}


### DELETE tasklist
DELETE http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65eb29faef4f5956065e7235

