### Application Root
GET http://localhost:3001


### Get List
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/task


### Get record
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/task/65eb3838845b612161bcf8d3



### Not Found URL
GET http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/not-found-url



### Post task
POST http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/task
Content-Type: application/json

{
    "title": "Task 2",
    "description": "My Task 1",
    "status": "todo",
    "priority": "low",
    "dueDate": "2024-10-10"
}


### PUT task
PUT http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/task/65eb3838845b612161bcf8d3
Content-Type: application/json

{
    "title": "Task 11",
    "description": "My Task 11",
    "status": "done",
    "priority": "high",
    "dueDate": "2024-10-11"
}


### DELETE task
DELETE http://localhost:3001/api/person/65f227bb5fecd7e6c9a0902e/tasklist/65f251b63fab077cc14df319/task/65eb3838845b612161bcf8d3

