name: Pipeline Server

on:
  push:
    branches:
      - production
      - main
  pull_request:
    branches:
      - production
      - main

jobs:
  pipeline_test_server:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: 'Create env file'
        run: |
          touch .env
          echo PORT=3001 >> .env
          echo NODE_ENV=test >> .env
          echo MONGO_URL_TEST="${{ secrets.MONGO_URL_TEST }}" >> .env
          cat .env

      - name: Install Dependencies
        run: npm install

      # - name: Check Lint
      #   run: npm run lint

      - name: Run test
        run: npm run test

      # - name: Deploy
      #   run: curl ${{ secrets.SERVER_DEPLOYMENT_HOOK }}
